By Rahul kumar 💻 ✈

github - https://github.com/Rahul5914

youtube - https://youtube.com/@biharwaleenginner?si=n-b4mPbcUZ35wt7P

linkedin - https://www.linkedin.com/in/rahul-kumar-3829b322a/

instagram: - @therahul5914

In [ ]:
import numpy as np

Creating a Matrix using numpy

In [ ]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [ ]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [ ]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.95891595 0.04750237 0.22344011]
 [0.61706045 0.78892712 0.79356268]
 [0.39986951 0.92162191 0.13069215]]


In [ ]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[74 68 37 53 97]
 [26 77 36 27 84]
 [87 77 72 78 15]
 [31 60 38 86 80]]


Matrix with all the values as 1

In [ ]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [ ]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [ ]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [ ]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [ ]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[69 34 33  7 59]
 [35 26  1 83 90]
 [38 42 94 12 85]
 [91 15 96 71 36]]


In [ ]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[69 35 38 91]
 [34 26 42 15]
 [33  1 94 96]
 [ 7 83 12 71]
 [59 90 85 36]]
