By Rahul kumar 💻 ✈

github - https://github.com/Rahul5914

youtube - https://youtube.com/@biharwaleenginner?si=n-b4mPbcUZ35wt7P

linkedin - https://www.linkedin.com/in/rahul-kumar-3829b322a/

instagram: - @therahul5914

Importing Numpy Library

In [ ]:
import numpy as np

Matrix Addition

Two Matrices can be added only if they have the same shape

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
A.shape

(2, 2)

In [ ]:
B.shape

(2, 2)

Adding two Matrices

In [ ]:
sum = A + B

In [ ]:
print(sum)

[[ 8 10]
 [12 14]]


In [ ]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [ ]:
print(matrix_1)

[[9 0 5]
 [8 0 7]
 [9 0 9]]


In [ ]:
print(matrix_2)

[[ 6  3 11]
 [ 5  2 16]
 [11  4  6]]


In [ ]:
sum = np.add(matrix_1, matrix_2)

In [ ]:
print(sum)

[[15  3 16]
 [13  2 23]
 [20  4 15]]


In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [ ]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because shape of matrix_3 and matrix_4 are different

size = 3,3 both have to equal not 3,4

**Matrix Subtraction**

In [ ]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [ ]:
print(A)

[[2 3]
 [4 5]]


In [ ]:
print(B)

[[6 7]
 [8 9]]


In [ ]:
difference = A - B

In [ ]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [ ]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [ ]:
print(matrix_1)

[[3 3 7]
 [1 6 4]
 [7 1 5]]


In [ ]:
print(matrix_2)

[[13 15  6]
 [ 9  5 18]
 [11  0  6]]


In [ ]:
diff = np.subtract(matrix_1, matrix_2)

In [ ]:
print(diff)

[[-10 -12   1]
 [ -8   1 -14]
 [ -4   1  -1]]


**Multiplying a matrix by a scalar**

In [ ]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[1 9 9 2]
 [9 8 1 8]
 [4 4 2 5]
 [0 9 8 9]]


In [ ]:
product = np.multiply(x,y)

In [ ]:
print(product)

[[ 5 45 45 10]
 [45 40  5 40]
 [20 20 10 25]
 [ 0 45 40 45]]


Multiplying 2 Matrices

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [ ]:
print(matrix_3)

[[0 1 2]
 [2 1 4]
 [1 0 0]]


In [ ]:
print(matrix_4)

[[4 4 3 2]
 [2 4 1 0]
 [2 3 1 3]]


In [ ]:
product = np.dot(matrix_3, matrix_4)

In [ ]:
print(product)

[[ 6 10  3  6]
 [18 24 11 16]
 [ 4  4  3  2]]


In [ ]:
product.shape

(3, 4)

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [ ]:
product = np.dot(matrix_3, matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

have not same dimension


**Element wise Matrix Multiplication**

In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [ ]:
print(matrix_3)

[[3 3 2]
 [4 4 4]
 [4 1 3]]


In [ ]:
print(matrix_4)

[[3 1 1]
 [4 4 2]
 [4 3 0]]


In [ ]:
product = np.multiply(matrix_3, matrix_4)

In [ ]:
print(product)

[[ 9  3  2]
 [16 16  8]
 [16  3  0]]


In [ ]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [ ]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 